# Generated by Django 4.2.1 on 2023-07-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaonline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendaonline.productor'),
        ),
    ]
